## namespace
namespace: zhenhao-tan-dev

## market image version
image:
  repository: public.ecr.aws/acentrik/oceanprotocol/operator-engine
  tag: ak-v1.0.0-non-root
  ## Specify a imagePullPolicy
  pullPolicy: Always

## Set desired pod ReplicaSet
replica: 1

## Enable/Disable Kubernetes Secrets Store CSI Driver. Currently only support AWS provider.
## ref: https://secrets-store-csi-driver.sigs.k8s.io
## ref: https://github.com/aws/secrets-store-csi-driver-provider-aws
secretstore:
  enabled: false
  provider: aws

## Secret relevant values or keys, depends on secretstore flag
secret:
  postgres:
    db:
      operatordb
      #objectName: parameter name
      #objectType: "secretsmanager" or "ssmparameter"
    user: postgres
    password: S47UHGJ2en
    host: postgresql
    port: "5432"
  operatorPrivateKey: "f9e30e7c158457370ba43848211b9c3c8a09aff0bc506242c8abdb2faeed818e"
  aws:
    accessKeyId: AKIAVR3PDAKYY27D6WNK
    secretAccessKey: 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
  ipfs:
    apiKey: ""
    apiClient: ""

## ConfigMap relevant values
config:
  aws:
    enabled: true
    region: ap-southeast-1
    bucket:
      output: sandbox-compute-v1-logs
      adminlogs: sandbox-compute-v1-logs
  ipfs:
    enabled: false
    output: <IPFS CLUSTER PROXY API URL>
    adminlogs: <IPFS CLUSTER PROXY API URL>
    outputPrefix: <IPFS Gateway URL>
    adminlogsPrefix: <IPFS Gateway URL>
    ## expiry time must be in hour (h) or minutes (m) unit.
    ## Default 60 days = 1440 hours
    expiryTime: "1440h"
  storageClass: gp2
  pod:
    configurationContainer: public.ecr.aws/acentrik/oceanprotocol/pod-configuration:new_timeouts-non-root
    publishContainer: public.ecr.aws/acentrik/oceanprotocol/pod-publishing:v4main-220708-non-root
  log:
    level: INFO
  debug:
    noCleanup: false
  serviceAccount: default
  maxJobDuration: "900"

## Configure pod resources
# resources:
#   limits:
#     cpu: 500m
#     memory: 500Mi
#   requests:
#     cpu: 500m
#     memory: 500Mi

storageclass:
  enabled: false
  name: standard
  reclaimPolicy: Delete
  ## AWS provisioner
  provisioner: kubernetes.io/aws-ebs
  parameters:
    fsType: ext4
    type: gp2
    encrypted: "true"
  allowedTopologies:
    enabled: true
    matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - ap-southeast-1a
  ## Azure provisioner
  #  provisioner: kubernetes.io/azure-disk
  #  parameters:
  #  kind: Managed
  #  storageaccounttype: StandardSSD_LRS
